### ISSUE TITLE
Assumes 10.0.0.0/16 block is available

### ISSUE THREAD

**Issue by frphu** [microservices-today/ngp-aws#16]
Creating the VPC and subnets has hardcoded CIDR block along with the subnets,  Also the subnets created maybe be too small as they are /24.

Can this be configurable through the cloudformation stack creation process?

**Comment by vysakhqb** [comment]
Good suggestion. We will make the VPC and subnet CIDR blocks as input parameters.

**Comment by vysakhqb** [comment]
#17
